name: ender_env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-types=0.6.0=py313h06a4308_1
  - anyio=4.10.0=py313h06a4308_0
  - brotlicffi=1.2.0.0=py313h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2026.01.04=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - charset-normalizer=3.4.4=py313h06a4308_0
  - distro=1.9.0=py313h06a4308_0
  - greenlet=3.2.4=py313hbdd6827_0
  - h11=0.16.0=py313h06a4308_1
  - httpcore=1.0.9=py313h06a4308_0
  - httpx=0.28.1=py313h06a4308_1
  - idna=3.11=py313h06a4308_0
  - jiter=0.12.0=py313h498d7c9_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h06a4308_0
  - langchain=0.3.27=py313h06a4308_0
  - langchain-core=0.3.77=py313h06a4308_0
  - langchain-openai=0.3.16=py313h06a4308_1
  - langchain-text-splitters=0.3.11=py313h06a4308_0
  - langsmith=0.6.0=py313h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openai=1.109.1=py313h06a4308_0
  - openssl=3.0.18=hd6dcaed_0
  - orjson=3.11.4=py313h828f358_1
  - packaging=25.0=py313h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py313h06a4308_0
  - pydantic=2.12.4=py313h06a4308_0
  - pydantic-core=2.41.5=py313h498d7c9_1
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.11=hcf712cf_100_cp313
  - python_abi=3.13=3_cp313
  - pyyaml=6.0.3=py313h591646f_0
  - readline=8.3=hc2a1206_0
  - regex=2025.11.3=py313h47b2149_0
  - requests=2.32.5=py313h06a4308_1
  - requests-toolbelt=1.0.0=py313h06a4308_0
  - setuptools=80.9.0=py313h06a4308_0
  - sniffio=1.3.1=py313h06a4308_0
  - sqlalchemy=2.0.45=py313h357f0b5_0
  - sqlite=3.51.1=he0a8d7e_0
  - tenacity=9.1.2=py313h06a4308_1
  - tiktoken=0.12.0=py313hc89162b_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py313h7040dfc_1
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing-inspection=0.4.2=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py313h06a4308_0
  - uuid-utils=0.12.0=py313h828f358_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.24.0=py313h3d778a8_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/pkw/anaconda3/envs/langchain_env
